// Generated by Wrangler by running `wrangler types`

interface Env {
	AUTHORIZATION_TOKEN: "ABC123";
	STUDIO_USER: "";
	STUDIO_PASS: "";
	STARBASE_DURABLE_OBJECT: DurableObjectNamespace<import("./src/index").StarbaseDurableObject>;
}
