// Generated by Wrangler by running `wrangler types`

interface Env {
	AUTHORIZATION_TOKEN: "ABC123";
	REGION: "auto";
	DATABASE_DURABLE_OBJECT: DurableObjectNamespace<import("./src/index").DatabaseDurableObject>;
	ALLOWLIST: Fetcher;
}
