// Generated by Wrangler by running `wrangler types`

interface Env {
	AUTHORIZATION_TOKEN: "ABC123";
	DATABASE_DURABLE_OBJECT: DurableObjectNamespace<import("./src/index").DatabaseDurableObject>;
	AUTH: Fetcher;
}
