#:schema node_modules/wrangler/config-schema.json
name = "starbasedb"
main = "src/index.ts"
compatibility_date = "2024-09-25"
account_id = ""

# Service Bindings
## DO NOT REMOVE: TEMPLATE SERVICES ##

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true

# Bind a Durable Object. Durable objects are a scale-to-zero compute primitive based on the actor model.
# Durable Objects can live for as long as needed. Use these when you need a long-running "server", such as in realtime apps.
# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#durable-objects
[[durable_objects.bindings]]
name = "DATABASE_DURABLE_OBJECT"
class_name = "DatabaseDurableObject"

# Durable Object migrations.
# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#migrations
[[migrations]]
tag = "v1"
new_sqlite_classes = ["DatabaseDurableObject"]

[vars]
AUTHORIZATION_TOKEN = "ABC123"
REGION = "auto"

# Uncomment the section below to create a user for logging into your database UI.
# You can access the Studio UI at: https://your_endpoint/studio
# STUDIO_USER = "admin"
# STUDIO_PASS = "123456"

# External database source details
# This enables Starbase to connect to an external data source
EXTERNAL_DB_TYPE = "postgres"
EXTERNAL_DB_HOST = ""
EXTERNAL_DB_NAME = ""
EXTERNAL_DB_USER = ""
EXTERNAL_DB_PASS = ""
EXTERNAL_DB_PORT = "0"