name = "starbasedb_allowlist_queries"
main = "./src/index.ts"
compatibility_date = "2024-09-25"

[durable_objects]
bindings = [{ name = "DATABASE_DURABLE_OBJECT", class_name = "DatabaseDurableObject", script_name = "starbasedb" }]
