// Generated by Wrangler by running `wrangler types`

interface Env {
    REQUIRE_EMAIL_CONFIRM: 1
    PASSWORD_REQUIRE_LENGTH: 13
    PASSWORD_REQUIRE_UPPERCASE: true
    PASSWORD_REQUIRE_LOWERCASE: true
    PASSWORD_REQUIRE_NUMBER: false
    PASSWORD_REQUIRE_SPECIAL: true
    DATABASE_DURABLE_OBJECT: DurableObjectNamespace /* DatabaseDurableObject from starbasedb */
}
