name = "starbasedb_auth"
main = "./src/index.ts"
compatibility_date = "2024-09-25"

[durable_objects]
bindings = [{ name = "DATABASE_DURABLE_OBJECT", class_name = "DatabaseDurableObject", script_name = "starbasedb" }]

[vars]
REQUIRE_EMAIL_CONFIRM = 1
PASSWORD_REQUIRE_LENGTH = 13
PASSWORD_REQUIRE_UPPERCASE = true
PASSWORD_REQUIRE_LOWERCASE = true
PASSWORD_REQUIRE_NUMBER = false
PASSWORD_REQUIRE_SPECIAL = true